name: Integration Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    pull_request:

jobs:
  build:
    name: Run Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - testPackage: t1
            testInclude: "-Dtest=/**/*Test1"
          - testPackage: t2
            testInclude: "-Dtest=/**/*Test2"
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.6.3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
         mvn test --batch-mode --fail-at-end ${{ matrix.testInclude }}

    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
